development:
  adapter: mysql2
  database: reminder_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: reminder_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: reminder_production
  username: root
  password: 
  encoding: utf8